# Generated by Django 4.1.2 on 2022-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ticker', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
            options={
                'unique_together': {('email', 'ticker')},
            },
        ),
    ]
